{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nuts-discovery-admin.serviceAccountName" . }}
  labels:
{{ include "nuts-discovery-admin.labels" . | indent 4 }}
{{- end -}}
